Running a bokeh server to interact with the points. Clicking on a point prints its content in a new tab

In [16]:
#!bokeh serve --show ../python_editor/interactive_plot.py

Exploring points close to each other but have different scores I found two similar files one got score 10 and the other got 0 I realized the one with high score has the line "pylint: skip-file" in it which makes pylint ignore the file and give it a score of 10

In [1]:
import pandas as pd

df = pd.read_pickle("../data/embeddings.pkl")
with pd.option_context("display.max_colwidth", None):
    display(df[["text", "pylint_score"]].iloc[[1167, 1515]])

,text,pylint_score
1167,"# pylint: skip-file\n# -*- coding: utf-8 -*-\n# Generated by Django 1.11.20 on 2019-02-25 18:21\n\n\nimport django.contrib.postgres.fields.jsonb\nfrom django.db import migrations, models\nimport django.db.models.deletion\n\nfrom ..models import install_supports_jsonfield\n\nclass Migration(migrations.Migration):\n\n dependencies = [\n ('passive_data_kit', '0044_dataserverapitoken'),\n ]\n\n if install_supports_jsonfield():\n operations = [\n migrations.CreateModel(\n name='AppConfiguration',\n fields=[\n ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n ('name', models.CharField(max_length=1024)),\n ('id_pattern', models.CharField(max_length=1024)),\n ('context_pattern', models.CharField(default='.*', max_length=1024)),\n ('configuration_json', django.contrib.postgres.fields.jsonb.JSONField()),\n ('evaluate_order', models.IntegerField(default=1)),\n ('is_valid', models.BooleanField(default=False)),\n ('is_enabled', models.BooleanField(default=True)),\n ],\n ),\n migrations.AlterField(\n model_name='datafile',\n name='data_bundle',\n field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='passive_data_kit.DataBundle'),\n ),\n migrations.AlterField(\n model_name='datafile',\n name='data_point',\n field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='passive_data_kit.DataPoint'),\n ),\n ]\n else:\n operations = [\n migrations.CreateModel(\n name='AppConfiguration',\n fields=[\n ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n ('name', models.CharField(max_length=1024)),\n ('id_pattern', models.CharField(max_length=1024)),\n ('context_pattern', models.CharField(default='.*', max_length=1024)),\n ('configuration_json', models.TextField(max_length=34359738368)),\n ('evaluate_order', models.IntegerField(default=1)),\n ('is_valid', models.BooleanField(default=False)),\n ('is_enabled', models.BooleanField(default=True)),\n ],\n ),\n migrations.AlterField(\n model_name='datafile',\n name='data_bundle',\n field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='passive_data_kit.DataBundle'),\n ),\n migrations.AlterField(\n model_name='datafile',\n name='data_point',\n field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to='passive_data_kit.DataPoint'),\n ),\n ]\n",10.0
1515,"# Generated by Django 3.0.2 on 2020-01-23 13:24\n\nfrom django.conf import settings\nfrom django.db import migrations, models\nimport django.db.models.deletion\n\n\nclass Migration(migrations.Migration):\n\n initial = True\n\n dependencies = [\n migrations.swappable_dependency(settings.AUTH_USER_MODEL),\n ]\n\n operations = [\n migrations.CreateModel(\n name='UserBan',\n fields=[\n ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n ('created_at', models.DateTimeField(auto_now_add=True, help_text='Model was created at this time.', verbose_name='Created at')),\n ('updated_at', models.DateTimeField(auto_now=True, help_text='Model was updated at this time.', verbose_name='Updated at')),\n ('end_date', models.DateTimeField(blank=True, help_text='The end date tells, until the ban is valid. If the end_date is empty, the ban is infinit.', null=True, verbose_name='End date of the ban')),\n ('banned_user', models.ForeignKey(help_text='This is the banned user or the receiver of the ban.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),\n ('creator', models.ForeignKey(help_text='This is the creator of the ban. If the creator is empty, the ban was created by the system.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),\n ],\n options={\n 'verbose_name': 'User Ban',\n 'verbose_name_plural': 'User Bans',\n },\n ),\n migrations.CreateModel(\n name='IPBan',\n fields=[\n ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),\n ('created_at', models.DateTimeField(auto_now_add=True, help_text='Model was created at this time.', verbose_name='Created at')),\n ('updated_at', models.DateTimeField(auto_now=True, help_text='Model was updated at this time.', verbose_name='Updated at')),\n ('end_date', models.DateTimeField(blank=True, help_text='The end date tells, until the ban is valid. If the end_date is empty, the ban is infinit.', null=True, verbose_name='End date of the ban')),\n ('ip', models.GenericIPAddressField(help_text='This is the banned ip. Every request from this IP will result in 403.', null=True, verbose_name='IP')),\n ('creator', models.ForeignKey(help_text='This is the creator of the ban. If the creator is empty, the ban was created by the system.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),\n ],\n options={\n 'verbose_name': 'IP Ban',\n 'verbose_name_plural': 'IP Bans',\n },\n ),\n ]\n",0.0

Looking at files containing lines that modify or disable pylint

In [2]:
df[df["text"].str.contains("pylint: ")]

,text,repo_name,path,license,NUM_CHARS,pylint_text,pylint_score,embedding
14,# python3\n# Copyright 2018 DeepMind Technolog...,deepmind/acme,acme/wrappers/open_spiel_wrapper_test.py,apache-2.0,2288,"{\n ""messages"": [\n {\n ""...",1.212121,"[-0.4022675, 0.05586323, 0.3001429, 0.02678033..."
20,# Copyright 2018 The TensorFlow Authors. All R...,tensorflow/tensorflow,tensorflow/python/data/kernel_tests/optional_t...,apache-2.0,19306,"{\n ""messages"": [\n {\n ""...",0.000000,"[-0.43053547, 0.097063415, 0.25605303, 0.04251..."
49,"""""""\nTests for search API functions.\n""""""\nimp...",mitodl/micromasters,search/indexing_api_test.py,bsd-3-clause,42482,"{\n ""messages"": [\n {\n ""...",9.281915,"[-0.38126895, 0.18519893, 0.2630613, 0.0129136..."
70,# Copyright 2019 The TensorFlow Authors. All R...,tensorflow/model-optimization,tensorflow_model_optimization/python/core/spar...,apache-2.0,11076,"{\n ""messages"": [\n {\n ""...",0.000000,"[-0.37057924, 0.15778385, 0.3215601, 0.0247170..."
109,"""""""\nSupport for eQ-3 Bluetooth Smart thermost...",tinloaf/home-assistant,homeassistant/components/climate/eq3btsmart.py,apache-2.0,6246,"{\n ""messages"": [\n {\n ""...",9.438202,"[-0.39783424, 0.14497884, 0.26236078, -0.00818..."
...,...,...,...,...,...,...,...,...
3593,# Copyright 2016 Google LLC\n# Modifications: ...,googleinterns/server-side-identity,gsi/transport/__init__.py,apache-2.0,3286,"{\n ""messages"": [\n {\n ""...",3.529412,"[-0.27274552, 0.113980986, 0.26735222, 0.03639..."
3615,# -*- coding: utf-8 -*-\n#\n# Licensed to the ...,Fokko/incubator-airflow,airflow/sentry.py,apache-2.0,5280,"{\n ""messages"": [\n {\n ""...",8.985507,"[-0.38166073, 0.121002145, 0.26954794, 0.03445..."
3631,# Copyright 2017 Google Inc.\n#\n# Licensed un...,cschnei3/forseti-security,google/cloud/security/common/gcp_type/instance...,apache-2.0,1802,"{\n ""messages"": [\n {\n ""...",6.666667,"[-0.2538891, 0.15636742, 0.26146954, -0.014796..."
3687,"""""""Attention combination strategies.\n\nThis m...",bastings/neuralmonkey,neuralmonkey/encoders/encoder_wrapper.py,bsd-3-clause,18095,"{\n ""messages"": [\n {\n ""...",8.502994,"[-0.38866633, 0.17020728, 0.2533167, 0.0638766..."
3692,"'''\nCreated on Sep 23, 2013\n\n@author: sean\...",GiovanniConserva/TestDeploy,venv/Lib/site-packages/binstar_client/tests/co...,bsd-3-clause,4112,"{\n ""messages"": [\n {\n ""...",6.847826,"[-0.35524032, 0.13558125, 0.2348123, 0.1021792..."

We exclude these files and add a function to check for this line in data_processing file

In [13]:
df = df[~df["text"].str.contains("pylint: ")]
df = df.reset_index(drop=True)
df.to_pickle("../data/embeddings_v2.pkl")

In [18]:
#!bokeh serve --show ../python_editor/interactive_plot.py

In [2]:
import pandas as pd

df = pd.read_pickle("../data/embeddings_v2.pkl")

In [3]:
df["text"][1182]

'# Copyright 2015 Google Inc. All Rights Reserved.\n#\n# Licensed under the Apache License, Version 2.0 (the "License");\n# you may not use this file except in compliance with the License.\n# You may obtain a copy of the License at\n#\n#     http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable law or agreed to in writing, software\n# distributed under the License is distributed on an "AS IS" BASIS,\n# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n# See the License for the specific language governing permissions and\n# limitations under the License.\n# ==============================================================================\n\n"""Libraries to build Recurrent Neural Networks."""\nfrom __future__ import absolute_import\nfrom __future__ import division\nfrom __future__ import print_function\n'

In [ ]:
import ast
from tqdm import tqdm
tqdm.pandas()

def has_executable_code(row: pd.Series) -> bool:
    # BOM (Byte Order Mark) issue.
    try:
        tree = ast.parse(row["text"].lstrip("\ufeff"))
    except SyntaxError:
        print(row)

    # Recursively check for meaningful statements
    for child in ast.walk(tree):
        # Skip docstrings
        if isinstance(child, ast.Expr) and isinstance(child.value, ast.Constant) and isinstance(child.value.value, str):
            continue
        
        # Skip pass statements
        if isinstance(child, ast.Pass):
            continue
        
        # Skip type-only function/class definitions
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            continue
        
        # If we find assignment, control flow, return, etc.
        if isinstance(child, (
            ast.Assign, ast.AugAssign, ast.AnnAssign,
            ast.Return, ast.If, ast.For, ast.While,
            ast.Try, ast.With, ast.Call, ast.Raise,
            ast.Assert, ast.Yield
        )):
            return True

    return False

df["executable_code"] = df.progress_apply(has_executable_code, axis=1)

100%|██████████| 3587/3587 [00:02<00:00, 1537.22it/s]

In [10]:
print(df["text"][2358])

# -*- coding: utf-8 -*-
""" Task 803 """
import math

def catprob(bayes, cat):
    """ oblicza logarytm prawodpodobieństwa P(C=c) """
    if cat not in bayes.class_count:
        return -1e300
    return math.log(bayes.class_count[cat] \
        / float(sum(bayes.class_count.values())))