We used the test split so far because it was small now we use the train split to stimulate users

In [1]:
from datasets import load_dataset

ds = load_dataset("tomekkorbak/python-github-code", split="train")
ds

Dataset({
    features: ['text', 'repo_name', 'path', 'language', 'license', 'size', 'score'],
    num_rows: 90000
})

Remove rows with no suitable license and with no executable code

In [2]:
import sys
sys.path.append("..")
from python_editor.data_filtering import format_df, filter_df

ds.set_format("pandas")
df = ds[:]
df = format_df(df)
df = filter_df(df)

df

,text,repo_name,path,license,NUM_CHARS
0,from . import _ccallback_c\n\nimport ctypes\n\...,Eric89GXL/scipy,scipy/_lib/_ccallback.py,bsd-3-clause,6196
1,# -*- coding: utf-8 -*-\nappid = 'example'\nap...,BlueHouseLab/sms-openapi,python-requests/conf.py,apache-2.0,324
2,# -*- coding: utf-8 -*-\nimport logging\nimpor...,tomashaber/raiden,raiden/network/protocol.py,mit,24753
3,# -*- coding: utf-8 -*-\nimport json\nimport l...,mediafactory/yats,modules/yats/caldav/storage.py,mit,12605
4,# -*- coding: utf-8 -*-\n# Copyright 2020 Gree...,our-city-app/oca-backend,src/rogerthat/bizz/payment/to.py,apache-2.0,1164
...,...,...,...,...,...
56443,import json\nfrom pprint import pprint\nfrom s...,mrricearoni/iTunesSearch,printRecentAlbums.py,mit,357
56444,"#! /usr/bin/env python\n\nimport sys, os, geto...",ioram7/keystone-federado-pgid2013,build/greenlet/run-tests.py,apache-2.0,1321
56445,# Copyright 2019 The TensorFlow Authors. All R...,tensorflow/tensorboard,tensorboard/plugins/mesh/summary_v2_test.py,apache-2.0,5916
56446,"""""""\nTests for efflux.telemetry.endpoint\n""""""\...",effluxsystems/pyefflux,tests/unit/test_base.py,mit,1403
56447,import pytz\n\nfrom pendulum import _safe_time...,sdispater/pendulum,tests/test_main.py,mit,268

In [3]:
from python_editor.data_processing import has_executable_code
from tqdm import tqdm
tqdm.pandas()

df["executable_code"] = df.progress_apply(has_executable_code, axis=1)
df = df[df["executable_code"]]

 15%|█▌        | 8745/56448 [00:08<00:42, 1127.41it/s]<unknown>:49: SyntaxWarning: invalid decimal literal
100%|██████████| 56448/56448 [00:52<00:00, 1068.38it/s]

Get a reasonable sample

In [4]:
DF_SIZE = 200
df = df.sample(n=DF_SIZE)
df

,text,repo_name,path,license,NUM_CHARS,executable_code
48870,"from elastic_boogaloo import classifiers, dist...",nkashy1/elastic-boogaloo,example.py,mit,706,True
22693,"# Copyright (c) 2011 OpenStack, LLC.\n# All Ri...",tomasdubec/openstack-cinder,cinder/scheduler/host_manager.py,apache-2.0,10868,True
11376,# Generated by Django 3.0.7 on 2020-09-27 13:3...,conikuvat/edegal,backend/larppikuvat/migrations/0001_initial.py,mit,1162,True
4477,from website.addons.base.serializer import Cit...,zachjanicki/osf.io,website/addons/mendeley/serializer.py,apache-2.0,155,True
32040,__author__ = 'Charlie'\n# Utils used with tens...,BerenLuthien/HyperColumns_ImageColorization,TensorflowUtils.py,bsd-3-clause,11368,True
...,...,...,...,...,...,...
23416,import logging\nimport re\n\nfrom datafeeds.pa...,the-blue-alliance/the-blue-alliance,old_py2/datafeeds/parsers/tba/tba_videos_parse...,mit,860,True
1986,def test_local_variable():\n x = 1\n x = 2,asedunov/intellij-community,python/testData/inspections/PyRedeclarationIns...,apache-2.0,46,True
2259,"#\n# Copyright (c) 2008-2015 Citrix Systems, I...",mahabs/nitro,nssrc/com/citrix/netscaler/nitro/resource/conf...,apache-2.0,1047,True
29005,# -*- coding: utf-8 -*-\n#\n# ----------------...,xunxunzgq/open-hackathon-bak_01,open-hackathon-server/src/hackathon/docker/hos...,mit,24562,True
31101,from mock import patch\n\nprint(patch.object)\...,paplorinc/intellij-community,python/testData/inspections/PyUnresolvedRefere...,apache-2.0,82,True

Make sure app is running

In [5]:
!docker compose -f /mnt/ssd/ME/ML_files/python-editor/Python-Editor/docker-compose.yml up --build -d

[+] Building 0.0s (0/1)
 => [internal] load local bake definitions                                 0.0s
[+] Building 0.2s (1/1)
 => [internal] load local bake definitions                                 0.0s
 => => reading from stdin 1.08kB                                           0.0s
[+] Building 0.3s (1/2)
 => [internal] load local bake definitions                                 0.0s
 => => reading from stdin 1.08kB                                           0.0s
[+] Building 0.4s (5/9)
 => [internal] load local bake definitions                                 0.0s
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  0.1s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
[+] Building 0.6s (13/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  0.2s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 0.7s (14/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  0.4s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 0.9s (14/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  0.5s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 1.0s (14/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  0.7s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 1.2s (14/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  0.8s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 1.3s (14/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  1.0s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 1.5s (14/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  1.1s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 1.6s (15/15)
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  1.2s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
[+] Building 1.7s (23/24)
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
 => [frontend internal] load .dockerignore                                 0.0s
 => => transferring context: 2B                                            0.0s
 => [frontend internal] load build context                                 0.0s
 => => transferring context: 892B                                          0.0s
 => [frontend 1/5] FROM docker.io/library/node:20-alpine@sha256:fb4cd12c8  0.0s
 => CACHED [frontend 2/5] WORKDIR /app                                     0.0s
 => CACHED [frontend 3/5] COPY package.json ./                             0.0s
 => CACHED [frontend 4/5] RUN npm install                                  0.0s
 => CACHED [frontend 5/5] COPY . .                                         0.0s
 => [frontend] exporting to image                                          0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:f0d1fae11ec6ba8a40598a9bf2278a0b4b23042edd37a  0.0s
 => => naming to docker.io/library/python-editor-frontend                  0.0s
 => [frontend] resolving provenance for metadata file                      0.0s
[+] Building 1.7s (24/24) FINISHED
 => [internal] load local bake definitions                                 0.0s
 => => reading from stdin 1.08kB                                           0.0s
 => [frontend internal] load build definition from Dockerfile              0.0s
 => => transferring dockerfile: 183B                                       0.0s
 => [backend internal] load build definition from Dockerfile               0.0s
 => => transferring dockerfile: 396B                                       0.0s
 => [frontend internal] load metadata for docker.io/library/node:20-alpin  1.2s
 => [backend internal] load metadata for docker.io/library/python:3.12-sl  0.0s
 => [backend internal] load .dockerignore                                  0.0s
 => => transferring context: 2B                                            0.0s
 => [backend internal] load build context                                  0.0s
 => => transferring context: 4.95kB                                        0.0s
 => [backend 1/6] FROM docker.io/library/python:3.12-slim                  0.0s
 => CACHED [backend 2/6] WORKDIR /app                                      0.0s
 => CACHED [backend 3/6] RUN apt-get update && apt-get install -y --no-in  0.0s
 => CACHED [backend 4/6] COPY requirements.txt .                           0.0s
 => CACHED [backend 5/6] RUN pip install --no-cache-dir -r requirements.t  0.0s
 => CACHED [backend 6/6] COPY app ./app                                    0.0s
 => [backend] exporting to image                                           0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6458e87f841cda3460b1406c04a481e39795952001b59  0.0s
 => => naming to docker.io/library/python-editor-backend                   0.0s
 => [backend] resolving provenance for metadata file                       0.0s
 => [frontend internal] load .dockerignore                                 0.0s
 => => transferring context: 2B                                            0.0s
 => [frontend internal] load build context                                 0.0s
 => => transferring context: 892B                                          0.0s
 => [frontend 1/5] FROM docker.io/library/node:20-alpine@sha256:fb4cd12c8  0.0s
 => CACHED [frontend 2/5] WORKDIR /app                                     0.0s
 => CACHED [frontend 3/5] COPY package.json ./                             0.0s
 => CACHED [frontend 4/5] RUN npm install                                  0.0s
 => CACHED [frontend 5/5] COPY . .                                         0.0s

`stimulate_users` takes df and iterates over each row and does the following:

1- If user is already registered it logs in then performs a submission

2- If user is not registered it registeres the user logs in then performs a submission

In [7]:
from monitoring.stimulate_users import stimulate_users

df_credentials = stimulate_users(df)
df_credentials

  0%|          | 0/200 [00:00<?, ?it/s]

100%|██████████| 200/200 [03:05<00:00,  1.08it/s]

             user_name  password
0              nkashy1  krIlDgb1
1           tomasdubec  0N0WTaa6
2            conikuvat  E716w5Bk
3          zachjanicki  id0wPiUL
4         BerenLuthien  pfPY1uyc
..                 ...       ...
191  the-blue-alliance  FaasBv9m
192           asedunov  dUhLCfeS
193             mahabs  m6qSjsFM
194          xunxunzgq  1lVByXYt
195          paplorinc  RF0AAZfs

[196 rows x 2 columns]

We connect to the db and see the number of submissons matches the df length

In [8]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/python_editor"
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM users AS total_users;"))
    for row in result:
        print(f"Number of users: {row[0]}")

with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM code_submissions AS total_submissions;"))
    for row in result:
        print(f"Number of submissions: {row[0]}")

Number of users: 196
Number of submissions: 200